Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,8 +1,8 @@
-# Version 0.1.3
+# Version 0.3.0
 name: UPM Deployment
 
 env:
-  PACKAGE_ROOT: "<PROJECT_NAME>/Assets/<PACKAGE_NAME>"
+  PACKAGE_ROOT: <PROJECT_NAME>/Assets/<PACKAGE_NAME>
 
 on:
   push:
@@ -63,6 +63,7 @@ jobs:
           then
             goo transform hide-folder "Samples"
             goo package ignore-folder . "Samples"
+            goo transform hide-folder "Tests"
           fi
 
       - name: Deploy Package
@@ -73,3 +74,10 @@ jobs:
           FOLDER: \"$PACKAGE_ROOT\"
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           MESSAGE: "Deploy: {sha} (v${{env.VERSION}})"
+      
+      - name: Tag UPM branch
+        run: |
+          git fetch origin upm
+          git checkout -f upm
+          git tag v${{env.VERSION}} HEAD
+          git push --tags || echo "Warning: tag failed. Does version ${{env.VERSION}} already exist in the repository?"
